import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className="overflow-y-scroll">
      <body className="flex h-fit py-5 flex-col items-center">
          <Navbar />
          <div className="w-full h-full  flex items-center justify-center pt-14">
            {children}
          </div>
      </body>
    </html>
  );
}
