CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  role VARCHAR(20) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS snippets (
  id SERIAL PRIMARY KEY,
  userid INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  language VARCHAR(50),
  title VARCHAR(255) NOT NULL,
  code TEXT,
  description TEXT,
  tags VARCHAR(50)[],
  created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);