name: Scheduled Job to Trigger Railway App

on:
  schedule:
    - cron: '*/10 * * * *' 
  workflow_dispatch: 

jobs:
  trigger_job:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Railway API endpoint
        run: |
          curl https://codeletserver-production.up.railway.app/api/v1/ping
